ManagementSystem/LMS_mastery.UI/Controllers/ParentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LMS_mastery.Data;
using Microsoft.AspNet.Identity;

namespace LMS_mastery.UI.Controllers
{
    public class ParentController : Controller
    {
        //
        // GET: /Parent/
        public ActionResult Index()
        {
            var repository = new ParentRepository();

            // get the list of courses. Pass in UserId
            var children = repository.GetChildren(User.Identity.GetUserId());
            return View(children);
        }
        public ActionResult Classes(string id)
        {
            var repository = new StudentRepository();

            // get the list of courses. Pass in UserId
            var courses = repository.GetStudentClasses(id);
            return View(courses);
        }

        public ActionResult Grades(int id)
        {
            var repository = new StudentRepository();

            var courses = repository.GetStudentGrades(id);
            return View(courses);
        }
	}
}

ManagementSystem/LMS_mastery.UI/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LMS_mastery.Data;
using Microsoft.AspNet.Identity;

namespace LMS_mastery.UI.Controllers
{
    public class StudentController : Controller
    {
        //
        // GET: /Student/
        public ActionResult Index()
        {
            var repository = new StudentRepository();

            // get the list of courses. Pass in UserId
            var courses = repository.GetStudentClasses(User.Identity.GetUserId());
            return View(courses);
        }

        public ActionResult Grades(int id)
        {
            var repository = new StudentRepository();

            var courses = repository.GetStudentGrades(id);
            return View(courses);
        }
	}
}

ManagementSystem/LMS_mastery.UI/Views/Parent/Classes.cshtml
@model IEnumerable<LMS_mastery.Models.DTOsView.StudentDashboard>
@{
    ViewBag.Title = "Index";
}

<h1>Student Dashboard</h1>

<h2>My Classes</h2>


<div class="row">
    <fieldset>
        <table class="col-sm-8 col-sm-offset-1">
            <tbody>
                @foreach (var course in Model)
                {
                    <tr>
                        <td><span class="glyphicon glyphicon-chevron-right"> </span><span id="fontSize">@course.Name</span></td>
                        <td id="bigger">@course.LetterGrade</td>
                        <td class="col-sm-offset-2 biggerLink">@Html.ActionLink("View Grades", "Grades", "Student", new { id = course.RosterId }, new { @class = "label label-info" })</td>
                    </tr>
                }
            </tbody>

        </table>
    </fieldset>
</div>


@section scripts{

    <link href="~/Content/StudentCSS.css" rel="stylesheet" />
}

ManagementSystem/LMS_mastery.UI/Views/Parent/Grades.cshtml
@model LMS_mastery.Models.DTOsView.StudentGrades

@{
    ViewBag.Title = "Grades";
}

<h2>@Model.Name - Grades</h2>


<div class="row">
    @foreach (var assignment in Model.Grades)
    {
        <div class="well well-lg col-sm-2">
            <h4>@assignment.Name</h4>
            <h3>@assignment.Percentage  |  <label id="letterGrade">@assignment.LetterGrade</label></h3>
        </div>
    }
</div>



@section scripts{

    <link href="~/Content/Grades.css" rel="stylesheet" />
}

ManagementSystem/LMS_mastery.UI/Views/Parent/Index.cshtml
@model IEnumerable<LMS_mastery.Models.DTOsView.ParentDashboard>

@{
    ViewBag.Title = "Index";
}

<h2>Parent Dashboard</h2>
<br/>
<h4>My Students</h4>
<table class="table">
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("View Classes", "Classes", "Parent", new { id = item.ChildId }, new { @class = "label label-info" })
        </td>
        
    </tr>
}

</table>